// Generated by view binder compiler. Do not edit!
package com.example.myappapp.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.ImageButton;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.constraintlayout.widget.ConstraintLayout;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.example.myappapp.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ActivityConfirmationBinding implements ViewBinding {
  @NonNull
  private final ConstraintLayout rootView;

  @NonNull
  public final ImageButton buttonBack;

  @NonNull
  public final Button buttonCancel;

  @NonNull
  public final Button buttonSubmit;

  @NonNull
  public final View divider;

  @NonNull
  public final TextView textViewConcessionTicketInfo;

  @NonNull
  public final TextView textViewDate;

  @NonNull
  public final TextView textViewEventName;

  @NonNull
  public final TextView textViewFullTicketInfo;

  @NonNull
  public final TextView textViewStudentTicketInfo;

  @NonNull
  public final TextView textViewTotalAmount;

  private ActivityConfirmationBinding(@NonNull ConstraintLayout rootView,
      @NonNull ImageButton buttonBack, @NonNull Button buttonCancel, @NonNull Button buttonSubmit,
      @NonNull View divider, @NonNull TextView textViewConcessionTicketInfo,
      @NonNull TextView textViewDate, @NonNull TextView textViewEventName,
      @NonNull TextView textViewFullTicketInfo, @NonNull TextView textViewStudentTicketInfo,
      @NonNull TextView textViewTotalAmount) {
    this.rootView = rootView;
    this.buttonBack = buttonBack;
    this.buttonCancel = buttonCancel;
    this.buttonSubmit = buttonSubmit;
    this.divider = divider;
    this.textViewConcessionTicketInfo = textViewConcessionTicketInfo;
    this.textViewDate = textViewDate;
    this.textViewEventName = textViewEventName;
    this.textViewFullTicketInfo = textViewFullTicketInfo;
    this.textViewStudentTicketInfo = textViewStudentTicketInfo;
    this.textViewTotalAmount = textViewTotalAmount;
  }

  @Override
  @NonNull
  public ConstraintLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ActivityConfirmationBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ActivityConfirmationBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.activity_confirmation, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ActivityConfirmationBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.buttonBack;
      ImageButton buttonBack = ViewBindings.findChildViewById(rootView, id);
      if (buttonBack == null) {
        break missingId;
      }

      id = R.id.buttonCancel;
      Button buttonCancel = ViewBindings.findChildViewById(rootView, id);
      if (buttonCancel == null) {
        break missingId;
      }

      id = R.id.buttonSubmit;
      Button buttonSubmit = ViewBindings.findChildViewById(rootView, id);
      if (buttonSubmit == null) {
        break missingId;
      }

      id = R.id.divider;
      View divider = ViewBindings.findChildViewById(rootView, id);
      if (divider == null) {
        break missingId;
      }

      id = R.id.textViewConcessionTicketInfo;
      TextView textViewConcessionTicketInfo = ViewBindings.findChildViewById(rootView, id);
      if (textViewConcessionTicketInfo == null) {
        break missingId;
      }

      id = R.id.textViewDate;
      TextView textViewDate = ViewBindings.findChildViewById(rootView, id);
      if (textViewDate == null) {
        break missingId;
      }

      id = R.id.textViewEventName;
      TextView textViewEventName = ViewBindings.findChildViewById(rootView, id);
      if (textViewEventName == null) {
        break missingId;
      }

      id = R.id.textViewFullTicketInfo;
      TextView textViewFullTicketInfo = ViewBindings.findChildViewById(rootView, id);
      if (textViewFullTicketInfo == null) {
        break missingId;
      }

      id = R.id.textViewStudentTicketInfo;
      TextView textViewStudentTicketInfo = ViewBindings.findChildViewById(rootView, id);
      if (textViewStudentTicketInfo == null) {
        break missingId;
      }

      id = R.id.textViewTotalAmount;
      TextView textViewTotalAmount = ViewBindings.findChildViewById(rootView, id);
      if (textViewTotalAmount == null) {
        break missingId;
      }

      return new ActivityConfirmationBinding((ConstraintLayout) rootView, buttonBack, buttonCancel,
          buttonSubmit, divider, textViewConcessionTicketInfo, textViewDate, textViewEventName,
          textViewFullTicketInfo, textViewStudentTicketInfo, textViewTotalAmount);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
