// Generated by view binder compiler. Do not edit!
package com.example.myappapp.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.EditText;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.constraintlayout.widget.ConstraintLayout;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.example.myappapp.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ActivityRegisterBinding implements ViewBinding {
  @NonNull
  private final ConstraintLayout rootView;

  @NonNull
  public final Button buttonCancel;

  @NonNull
  public final Button buttonCreateAccount;

  @NonNull
  public final EditText editTextNewAccount;

  @NonNull
  public final EditText editTextNewPassword;

  @NonNull
  public final TextView textViewRegisterTitle;

  private ActivityRegisterBinding(@NonNull ConstraintLayout rootView, @NonNull Button buttonCancel,
      @NonNull Button buttonCreateAccount, @NonNull EditText editTextNewAccount,
      @NonNull EditText editTextNewPassword, @NonNull TextView textViewRegisterTitle) {
    this.rootView = rootView;
    this.buttonCancel = buttonCancel;
    this.buttonCreateAccount = buttonCreateAccount;
    this.editTextNewAccount = editTextNewAccount;
    this.editTextNewPassword = editTextNewPassword;
    this.textViewRegisterTitle = textViewRegisterTitle;
  }

  @Override
  @NonNull
  public ConstraintLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ActivityRegisterBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ActivityRegisterBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.activity_register, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ActivityRegisterBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.buttonCancel;
      Button buttonCancel = ViewBindings.findChildViewById(rootView, id);
      if (buttonCancel == null) {
        break missingId;
      }

      id = R.id.buttonCreateAccount;
      Button buttonCreateAccount = ViewBindings.findChildViewById(rootView, id);
      if (buttonCreateAccount == null) {
        break missingId;
      }

      id = R.id.editTextNewAccount;
      EditText editTextNewAccount = ViewBindings.findChildViewById(rootView, id);
      if (editTextNewAccount == null) {
        break missingId;
      }

      id = R.id.editTextNewPassword;
      EditText editTextNewPassword = ViewBindings.findChildViewById(rootView, id);
      if (editTextNewPassword == null) {
        break missingId;
      }

      id = R.id.textViewRegisterTitle;
      TextView textViewRegisterTitle = ViewBindings.findChildViewById(rootView, id);
      if (textViewRegisterTitle == null) {
        break missingId;
      }

      return new ActivityRegisterBinding((ConstraintLayout) rootView, buttonCancel,
          buttonCreateAccount, editTextNewAccount, editTextNewPassword, textViewRegisterTitle);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
