// Generated by view binder compiler. Do not edit!
package com.example.myappapp.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.coordinatorlayout.widget.CoordinatorLayout;
import androidx.recyclerview.widget.RecyclerView;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.example.myappapp.R;
import com.google.android.material.floatingactionbutton.FloatingActionButton;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ActivityEventListBinding implements ViewBinding {
  @NonNull
  private final CoordinatorLayout rootView;

  @NonNull
  public final Button buttonPurchaseHistory;

  @NonNull
  public final FloatingActionButton fabProfile;

  @NonNull
  public final RecyclerView recyclerViewEvents;

  @NonNull
  public final TextView textViewListTitle;

  private ActivityEventListBinding(@NonNull CoordinatorLayout rootView,
      @NonNull Button buttonPurchaseHistory, @NonNull FloatingActionButton fabProfile,
      @NonNull RecyclerView recyclerViewEvents, @NonNull TextView textViewListTitle) {
    this.rootView = rootView;
    this.buttonPurchaseHistory = buttonPurchaseHistory;
    this.fabProfile = fabProfile;
    this.recyclerViewEvents = recyclerViewEvents;
    this.textViewListTitle = textViewListTitle;
  }

  @Override
  @NonNull
  public CoordinatorLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ActivityEventListBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ActivityEventListBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.activity_event_list, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ActivityEventListBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.buttonPurchaseHistory;
      Button buttonPurchaseHistory = ViewBindings.findChildViewById(rootView, id);
      if (buttonPurchaseHistory == null) {
        break missingId;
      }

      id = R.id.fabProfile;
      FloatingActionButton fabProfile = ViewBindings.findChildViewById(rootView, id);
      if (fabProfile == null) {
        break missingId;
      }

      id = R.id.recyclerViewEvents;
      RecyclerView recyclerViewEvents = ViewBindings.findChildViewById(rootView, id);
      if (recyclerViewEvents == null) {
        break missingId;
      }

      id = R.id.textViewListTitle;
      TextView textViewListTitle = ViewBindings.findChildViewById(rootView, id);
      if (textViewListTitle == null) {
        break missingId;
      }

      return new ActivityEventListBinding((CoordinatorLayout) rootView, buttonPurchaseHistory,
          fabProfile, recyclerViewEvents, textViewListTitle);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
