// Generated by view binder compiler. Do not edit!
package com.example.myappapp.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.constraintlayout.widget.ConstraintLayout;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.example.myappapp.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ActivityFinalPageBinding implements ViewBinding {
  @NonNull
  private final ConstraintLayout rootView;

  @NonNull
  public final Button buttonFinish;

  @NonNull
  public final TextView textViewEmailInfo;

  @NonNull
  public final TextView textViewSuccessTitle;

  private ActivityFinalPageBinding(@NonNull ConstraintLayout rootView, @NonNull Button buttonFinish,
      @NonNull TextView textViewEmailInfo, @NonNull TextView textViewSuccessTitle) {
    this.rootView = rootView;
    this.buttonFinish = buttonFinish;
    this.textViewEmailInfo = textViewEmailInfo;
    this.textViewSuccessTitle = textViewSuccessTitle;
  }

  @Override
  @NonNull
  public ConstraintLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ActivityFinalPageBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ActivityFinalPageBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.activity_final_page, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ActivityFinalPageBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.buttonFinish;
      Button buttonFinish = ViewBindings.findChildViewById(rootView, id);
      if (buttonFinish == null) {
        break missingId;
      }

      id = R.id.textViewEmailInfo;
      TextView textViewEmailInfo = ViewBindings.findChildViewById(rootView, id);
      if (textViewEmailInfo == null) {
        break missingId;
      }

      id = R.id.textViewSuccessTitle;
      TextView textViewSuccessTitle = ViewBindings.findChildViewById(rootView, id);
      if (textViewSuccessTitle == null) {
        break missingId;
      }

      return new ActivityFinalPageBinding((ConstraintLayout) rootView, buttonFinish,
          textViewEmailInfo, textViewSuccessTitle);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
