// Generated by view binder compiler. Do not edit!
package com.example.myappapp.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.constraintlayout.widget.ConstraintLayout;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.example.myappapp.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ActivityProfileBinding implements ViewBinding {
  @NonNull
  private final ConstraintLayout rootView;

  @NonNull
  public final Button buttonLogout;

  @NonNull
  public final TextView textViewAccount;

  @NonNull
  public final TextView textViewAccountLabel;

  @NonNull
  public final TextView textViewProfileTitle;

  private ActivityProfileBinding(@NonNull ConstraintLayout rootView, @NonNull Button buttonLogout,
      @NonNull TextView textViewAccount, @NonNull TextView textViewAccountLabel,
      @NonNull TextView textViewProfileTitle) {
    this.rootView = rootView;
    this.buttonLogout = buttonLogout;
    this.textViewAccount = textViewAccount;
    this.textViewAccountLabel = textViewAccountLabel;
    this.textViewProfileTitle = textViewProfileTitle;
  }

  @Override
  @NonNull
  public ConstraintLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ActivityProfileBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ActivityProfileBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.activity_profile, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ActivityProfileBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.buttonLogout;
      Button buttonLogout = ViewBindings.findChildViewById(rootView, id);
      if (buttonLogout == null) {
        break missingId;
      }

      id = R.id.textViewAccount;
      TextView textViewAccount = ViewBindings.findChildViewById(rootView, id);
      if (textViewAccount == null) {
        break missingId;
      }

      id = R.id.textViewAccountLabel;
      TextView textViewAccountLabel = ViewBindings.findChildViewById(rootView, id);
      if (textViewAccountLabel == null) {
        break missingId;
      }

      id = R.id.textViewProfileTitle;
      TextView textViewProfileTitle = ViewBindings.findChildViewById(rootView, id);
      if (textViewProfileTitle == null) {
        break missingId;
      }

      return new ActivityProfileBinding((ConstraintLayout) rootView, buttonLogout, textViewAccount,
          textViewAccountLabel, textViewProfileTitle);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
