// Generated by view binder compiler. Do not edit!
package com.example.myappapp.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.ImageButton;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.constraintlayout.widget.ConstraintLayout;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.example.myappapp.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ActivityBookingBinding implements ViewBinding {
  @NonNull
  private final ConstraintLayout rootView;

  @NonNull
  public final ImageButton buttonBack;

  @NonNull
  public final Button buttonConfirm;

  @NonNull
  public final Button buttonMinusConcession;

  @NonNull
  public final Button buttonMinusFull;

  @NonNull
  public final Button buttonMinusStudent;

  @NonNull
  public final Button buttonPlusConcession;

  @NonNull
  public final Button buttonPlusFull;

  @NonNull
  public final Button buttonPlusStudent;

  @NonNull
  public final TextView labelConcessionTicket;

  @NonNull
  public final TextView labelFullTicket;

  @NonNull
  public final TextView labelStudentTicket;

  @NonNull
  public final TextView textQuantityConcession;

  @NonNull
  public final TextView textQuantityFull;

  @NonNull
  public final TextView textQuantityStudent;

  @NonNull
  public final TextView textViewBookingDate;

  @NonNull
  public final TextView textViewBookingEventName;

  private ActivityBookingBinding(@NonNull ConstraintLayout rootView,
      @NonNull ImageButton buttonBack, @NonNull Button buttonConfirm,
      @NonNull Button buttonMinusConcession, @NonNull Button buttonMinusFull,
      @NonNull Button buttonMinusStudent, @NonNull Button buttonPlusConcession,
      @NonNull Button buttonPlusFull, @NonNull Button buttonPlusStudent,
      @NonNull TextView labelConcessionTicket, @NonNull TextView labelFullTicket,
      @NonNull TextView labelStudentTicket, @NonNull TextView textQuantityConcession,
      @NonNull TextView textQuantityFull, @NonNull TextView textQuantityStudent,
      @NonNull TextView textViewBookingDate, @NonNull TextView textViewBookingEventName) {
    this.rootView = rootView;
    this.buttonBack = buttonBack;
    this.buttonConfirm = buttonConfirm;
    this.buttonMinusConcession = buttonMinusConcession;
    this.buttonMinusFull = buttonMinusFull;
    this.buttonMinusStudent = buttonMinusStudent;
    this.buttonPlusConcession = buttonPlusConcession;
    this.buttonPlusFull = buttonPlusFull;
    this.buttonPlusStudent = buttonPlusStudent;
    this.labelConcessionTicket = labelConcessionTicket;
    this.labelFullTicket = labelFullTicket;
    this.labelStudentTicket = labelStudentTicket;
    this.textQuantityConcession = textQuantityConcession;
    this.textQuantityFull = textQuantityFull;
    this.textQuantityStudent = textQuantityStudent;
    this.textViewBookingDate = textViewBookingDate;
    this.textViewBookingEventName = textViewBookingEventName;
  }

  @Override
  @NonNull
  public ConstraintLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ActivityBookingBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ActivityBookingBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.activity_booking, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ActivityBookingBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.buttonBack;
      ImageButton buttonBack = ViewBindings.findChildViewById(rootView, id);
      if (buttonBack == null) {
        break missingId;
      }

      id = R.id.buttonConfirm;
      Button buttonConfirm = ViewBindings.findChildViewById(rootView, id);
      if (buttonConfirm == null) {
        break missingId;
      }

      id = R.id.buttonMinusConcession;
      Button buttonMinusConcession = ViewBindings.findChildViewById(rootView, id);
      if (buttonMinusConcession == null) {
        break missingId;
      }

      id = R.id.buttonMinusFull;
      Button buttonMinusFull = ViewBindings.findChildViewById(rootView, id);
      if (buttonMinusFull == null) {
        break missingId;
      }

      id = R.id.buttonMinusStudent;
      Button buttonMinusStudent = ViewBindings.findChildViewById(rootView, id);
      if (buttonMinusStudent == null) {
        break missingId;
      }

      id = R.id.buttonPlusConcession;
      Button buttonPlusConcession = ViewBindings.findChildViewById(rootView, id);
      if (buttonPlusConcession == null) {
        break missingId;
      }

      id = R.id.buttonPlusFull;
      Button buttonPlusFull = ViewBindings.findChildViewById(rootView, id);
      if (buttonPlusFull == null) {
        break missingId;
      }

      id = R.id.buttonPlusStudent;
      Button buttonPlusStudent = ViewBindings.findChildViewById(rootView, id);
      if (buttonPlusStudent == null) {
        break missingId;
      }

      id = R.id.labelConcessionTicket;
      TextView labelConcessionTicket = ViewBindings.findChildViewById(rootView, id);
      if (labelConcessionTicket == null) {
        break missingId;
      }

      id = R.id.labelFullTicket;
      TextView labelFullTicket = ViewBindings.findChildViewById(rootView, id);
      if (labelFullTicket == null) {
        break missingId;
      }

      id = R.id.labelStudentTicket;
      TextView labelStudentTicket = ViewBindings.findChildViewById(rootView, id);
      if (labelStudentTicket == null) {
        break missingId;
      }

      id = R.id.textQuantityConcession;
      TextView textQuantityConcession = ViewBindings.findChildViewById(rootView, id);
      if (textQuantityConcession == null) {
        break missingId;
      }

      id = R.id.textQuantityFull;
      TextView textQuantityFull = ViewBindings.findChildViewById(rootView, id);
      if (textQuantityFull == null) {
        break missingId;
      }

      id = R.id.textQuantityStudent;
      TextView textQuantityStudent = ViewBindings.findChildViewById(rootView, id);
      if (textQuantityStudent == null) {
        break missingId;
      }

      id = R.id.textViewBookingDate;
      TextView textViewBookingDate = ViewBindings.findChildViewById(rootView, id);
      if (textViewBookingDate == null) {
        break missingId;
      }

      id = R.id.textViewBookingEventName;
      TextView textViewBookingEventName = ViewBindings.findChildViewById(rootView, id);
      if (textViewBookingEventName == null) {
        break missingId;
      }

      return new ActivityBookingBinding((ConstraintLayout) rootView, buttonBack, buttonConfirm,
          buttonMinusConcession, buttonMinusFull, buttonMinusStudent, buttonPlusConcession,
          buttonPlusFull, buttonPlusStudent, labelConcessionTicket, labelFullTicket,
          labelStudentTicket, textQuantityConcession, textQuantityFull, textQuantityStudent,
          textViewBookingDate, textViewBookingEventName);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
