// Generated by view binder compiler. Do not edit!
package com.example.myappapp.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.HorizontalScrollView;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.constraintlayout.widget.ConstraintLayout;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.example.myappapp.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ActivityEventDetailBinding implements ViewBinding {
  @NonNull
  private final ConstraintLayout rootView;

  @NonNull
  public final Button buttonBack;

  @NonNull
  public final Button buttonBookNow;

  @NonNull
  public final LinearLayout dateButtonsContainer;

  @NonNull
  public final View divider;

  @NonNull
  public final HorizontalScrollView horizontalScrollView;

  @NonNull
  public final ImageView imageViewDetail;

  @NonNull
  public final TextView textViewNameDetail;

  private ActivityEventDetailBinding(@NonNull ConstraintLayout rootView, @NonNull Button buttonBack,
      @NonNull Button buttonBookNow, @NonNull LinearLayout dateButtonsContainer,
      @NonNull View divider, @NonNull HorizontalScrollView horizontalScrollView,
      @NonNull ImageView imageViewDetail, @NonNull TextView textViewNameDetail) {
    this.rootView = rootView;
    this.buttonBack = buttonBack;
    this.buttonBookNow = buttonBookNow;
    this.dateButtonsContainer = dateButtonsContainer;
    this.divider = divider;
    this.horizontalScrollView = horizontalScrollView;
    this.imageViewDetail = imageViewDetail;
    this.textViewNameDetail = textViewNameDetail;
  }

  @Override
  @NonNull
  public ConstraintLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ActivityEventDetailBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ActivityEventDetailBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.activity_event_detail, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ActivityEventDetailBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.buttonBack;
      Button buttonBack = ViewBindings.findChildViewById(rootView, id);
      if (buttonBack == null) {
        break missingId;
      }

      id = R.id.buttonBookNow;
      Button buttonBookNow = ViewBindings.findChildViewById(rootView, id);
      if (buttonBookNow == null) {
        break missingId;
      }

      id = R.id.dateButtonsContainer;
      LinearLayout dateButtonsContainer = ViewBindings.findChildViewById(rootView, id);
      if (dateButtonsContainer == null) {
        break missingId;
      }

      id = R.id.divider;
      View divider = ViewBindings.findChildViewById(rootView, id);
      if (divider == null) {
        break missingId;
      }

      id = R.id.horizontalScrollView;
      HorizontalScrollView horizontalScrollView = ViewBindings.findChildViewById(rootView, id);
      if (horizontalScrollView == null) {
        break missingId;
      }

      id = R.id.imageViewDetail;
      ImageView imageViewDetail = ViewBindings.findChildViewById(rootView, id);
      if (imageViewDetail == null) {
        break missingId;
      }

      id = R.id.textViewNameDetail;
      TextView textViewNameDetail = ViewBindings.findChildViewById(rootView, id);
      if (textViewNameDetail == null) {
        break missingId;
      }

      return new ActivityEventDetailBinding((ConstraintLayout) rootView, buttonBack, buttonBookNow,
          dateButtonsContainer, divider, horizontalScrollView, imageViewDetail, textViewNameDetail);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
