// Generated by view binder compiler. Do not edit!
package com.example.myappapp.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.ImageButton;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.example.myappapp.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class BottomSheetProfileBinding implements ViewBinding {
  @NonNull
  private final LinearLayout rootView;

  @NonNull
  public final ImageButton buttonHome;

  @NonNull
  public final ImageButton buttonProfileTab;

  @NonNull
  public final Button buttonPurchaseHistory;

  @NonNull
  public final ImageView imageViewProfileAvatar;

  @NonNull
  public final TextView textViewProfileEmail;

  private BottomSheetProfileBinding(@NonNull LinearLayout rootView, @NonNull ImageButton buttonHome,
      @NonNull ImageButton buttonProfileTab, @NonNull Button buttonPurchaseHistory,
      @NonNull ImageView imageViewProfileAvatar, @NonNull TextView textViewProfileEmail) {
    this.rootView = rootView;
    this.buttonHome = buttonHome;
    this.buttonProfileTab = buttonProfileTab;
    this.buttonPurchaseHistory = buttonPurchaseHistory;
    this.imageViewProfileAvatar = imageViewProfileAvatar;
    this.textViewProfileEmail = textViewProfileEmail;
  }

  @Override
  @NonNull
  public LinearLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static BottomSheetProfileBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static BottomSheetProfileBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.bottom_sheet_profile, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static BottomSheetProfileBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.buttonHome;
      ImageButton buttonHome = ViewBindings.findChildViewById(rootView, id);
      if (buttonHome == null) {
        break missingId;
      }

      id = R.id.buttonProfileTab;
      ImageButton buttonProfileTab = ViewBindings.findChildViewById(rootView, id);
      if (buttonProfileTab == null) {
        break missingId;
      }

      id = R.id.buttonPurchaseHistory;
      Button buttonPurchaseHistory = ViewBindings.findChildViewById(rootView, id);
      if (buttonPurchaseHistory == null) {
        break missingId;
      }

      id = R.id.imageViewProfileAvatar;
      ImageView imageViewProfileAvatar = ViewBindings.findChildViewById(rootView, id);
      if (imageViewProfileAvatar == null) {
        break missingId;
      }

      id = R.id.textViewProfileEmail;
      TextView textViewProfileEmail = ViewBindings.findChildViewById(rootView, id);
      if (textViewProfileEmail == null) {
        break missingId;
      }

      return new BottomSheetProfileBinding((LinearLayout) rootView, buttonHome, buttonProfileTab,
          buttonPurchaseHistory, imageViewProfileAvatar, textViewProfileEmail);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
