// Generated by view binder compiler. Do not edit!
package com.example.myappapp.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.ImageView;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.example.myappapp.R;
import com.google.android.material.card.MaterialCardView;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ListItemEventBinding implements ViewBinding {
  @NonNull
  private final MaterialCardView rootView;

  @NonNull
  public final ImageView imageViewEvent;

  @NonNull
  public final TextView textViewEventDate;

  @NonNull
  public final TextView textViewEventName;

  private ListItemEventBinding(@NonNull MaterialCardView rootView,
      @NonNull ImageView imageViewEvent, @NonNull TextView textViewEventDate,
      @NonNull TextView textViewEventName) {
    this.rootView = rootView;
    this.imageViewEvent = imageViewEvent;
    this.textViewEventDate = textViewEventDate;
    this.textViewEventName = textViewEventName;
  }

  @Override
  @NonNull
  public MaterialCardView getRoot() {
    return rootView;
  }

  @NonNull
  public static ListItemEventBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ListItemEventBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.list_item_event, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ListItemEventBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.imageViewEvent;
      ImageView imageViewEvent = ViewBindings.findChildViewById(rootView, id);
      if (imageViewEvent == null) {
        break missingId;
      }

      id = R.id.textViewEventDate;
      TextView textViewEventDate = ViewBindings.findChildViewById(rootView, id);
      if (textViewEventDate == null) {
        break missingId;
      }

      id = R.id.textViewEventName;
      TextView textViewEventName = ViewBindings.findChildViewById(rootView, id);
      if (textViewEventName == null) {
        break missingId;
      }

      return new ListItemEventBinding((MaterialCardView) rootView, imageViewEvent,
          textViewEventDate, textViewEventName);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
